### ISSUE TITLE
Year info is wrong

### ISSUE THREAD

**Issue by xoex** [hmerritt/php-imdb-api#18]
Hi.
There's an error in api that show the year of the movie in a wrong way:

'year' => string 'Cast & crew'

**Comment by hmerritt** [comment]
Thank you for pointing this out -> fixing it now :)

**Comment by xoex** [comment]
By the way, Why bother when you can decode json data in page instead of scraping content?
something like this works nice :
            $script = $dom->find("script[type=\"application/ld+json\"]", 0);
            $json = json_decode($script->innertext);

note that $dom is parsed dom from page. but with finding script and decode the inside json, you could have all the data you need.

**Comment by hmerritt** [comment]
I noticed that JSON while fixing this -> initially got excited but it doesn't have all the data I need.

I might use it anyway and then merge with the existing method (since it's probably more reliable)

**Comment by hmerritt** [comment]
Anyhow, I've fixed this issue in version `v1.2.8`
